#ifndef VBH_PERF_TEST_COMM_ID_DEF_H_39873427982341213652314756
#define VBH_PERF_TEST_COMM_ID_DEF_H_39873427982341213652314756

#include "dsc/dsc_comm_def.h"

#include "vbh_comm/vbh_comm_id_def.h"

namespace VBH_TEST
{
	enum
	{
		VBH_TEST_STATIC_NODE_TYPE = VBH::EN_MIN_VBH_APP_TYPE + 1,
		VBH_PERF_TEST_REGIST_CLIENT_NODE_TYPE,
		VBH_PERF_TEST_CLIENT_NODE_TYPE,
		VBH_LOAD_OUTER_CC_CLIENT_NODE_TYPE,

		VBH_PERF_TEST_STATIC_SERVICE_TYPE = VBH::EN_MIN_VBH_CLIENT_SERVICE_TYPE + 1,
		VBH_PERF_TEST_REGIST_CLIENT_SERVICE_TYPE,
		VBH_PERF_TEST_TRADE_CLIENT_SERVICE_TYPE,
		VBH_PERF_TEST_UPDATE_USER_CLIENT_SERVICE_TYPE,
		VBH_PERF_TEST_QUERY_USER_CLIENT_SERVICE_TYPE,
		VBH_PERF_TEST_QUERY_TRADE_CLIENT_SERVICE_TYPE,
		VBH_PERF_TEST_QUERY_BLOCK_CLIENT_SERVICE_TYPE,
		VBH_LOAD_OUTER_CC_CLIENT_SERVICE_TYPE,
	};

	enum
	{
		EN_TRADE_SUM_MSG = DSC::EN_MIN_USER_MSG + 1,
		EN_QUERY_SUM_MSG
	};
}

#endif
