#ifndef COMM_ID_DEF_H_342789423809732182139785892349782317556823482318875486723456
#define COMM_ID_DEF_H_342789423809732182139785892349782317556823482318875486723456

#include "dsc/dsc_comm_def.h"

#define DEF_INVALID_PEER_ID 0
#define DEF_INVALID_BLOCK_ID 0
#define DEF_INVALID_WRITE_SET_ID 0
#define DEF_INVALID_CC_ACTION_ID 0
#define DEF_INVALID_HISTORY_TABLE_INDEX 0

namespace VBH
{
	enum //APP_TYPE即NODE_TYEP
	{
		/* order */
		EN_ORDER_APP_TYPE = 1,

		/* endorser */
		EN_ENDORSER_APP_TYPE = 11,

		/* committer */
		EN_COMMITTER_APP_TYPE = 31,

		/* cc */
		EN_CC_APP_TYPE = 41, //TODO: 将来CC-进程的形式，以及CC的APP-ID,Service-ID还待定

		/* explorer */
		EN_EXPLORER_APP_TYPE = 51,

		/* sdk */
		EN_VBH_USER_INFO_SDK_APP_TYPE = 121,

		EN_VBH_SDK_APP_TYPE = 222,
		/* VBH用户层取 app-type的最小值 */
		EN_MIN_VBH_APP_TYPE = 500

	};

	enum //服务端的service-type
	{
		/* order */
		EN_ORDER_CHANNEL_PROCESS_SERVICE_CONTAINER_TYPE = DSC::EN_MIN_USER_TASK_TYPE + 1,
		EN_ORDER_MASTER_CHANNEL_PROCESS_SERVICE_TYPE,
		EN_ORDER_SLAVE_CHANNEL_PROCESS_SERVICE_TYPE,

		/* endorser */
		EN_CRYPT_ENDORSER_SERVICE_CONTAINER_TYPE,
		EN_ENDORSER_SERVICE_CONTAINER_TYPE,
		EN_CRYPT_ENDORSER_SERVICE_TYPE,
		EN_ENDORSER_SERVICE_TYPE,
		EN_CRYPT_TRANSFER_AGENT_SERVICE_TYPE,
		EN_TRANSFER_AGENT_SERVICE_TYPE,

		/* committer */
		EN_COMMITTER_SERVICE_CONTAINER_TYPE,
		EN_COMMITTER_SERVICE_TYPE,
		EN_COMMITTER_AGENT_SERVICE_TYPE,

		EN_MIN_VBH_INNER_CC_SERVICE_TYPE = 200, //最小的inner-cc-type
		EN_MIN_VBH_OUTER_CC_SERVICE_TYPE
	};

	enum //客户端的service-type //中台是VBH的客户端
	{
		/* client sdk */
		EN_VBH_API_SERVICE_TYPE = DSC::EN_MIN_USER_TASK_TYPE + 1,
		EN_VBH_CRYPT_CLIENT_SERVICE_TYPE,
		EN_VBH_CLIENT_SERVICE_TYPE,
		EN_VBH_ADAPTER_SERVICE_TYPE,

		/* explorer */
		EN_VBH_EXPLORER_HTTP_JSON_SERVICE_TYPE,
		EN_VBH_EXPLORER_HTTP_JSON_ACCEPTOR_SERVICE_TYPE,

		EN_MIN_VBH_CLIENT_SERVICE_TYPE = DSC::EN_MIN_USER_TASK_TYPE + 16, //客户端上层使用的最小service
	};

	enum
	{
		/* 初始化流程涉及消息 */
		EN_REGISTER_CS_CPS_REQ = DSC::EN_MIN_USER_MSG + 1,
		EN_SYNC_BLOCK_ON_REGIST_CPS_CS_NOTIFY,
		EN_SYNC_BLOCK_ON_REGIST_CPS_CS_ON_ORDER_MASTER_STATE_NOTIFY,
		EN_INVALID_PEER_CPS_CS_NOTIFY,
		EN_BACKSPACE_BLOCK_CPS_CS_NOTIFY,
		EN_MASTER_SYNC_VERSION_TABLE_CPS_CS_REQ,
		EN_MASTER_SYNC_VERSION_TABLE_CS_CPS_RSP,
		EN_SLAVE_SYNC_VERSION_TABLE_CPS_CS_REQ,
		EN_SLAVE_SYNC_VERSION_TABLE_CS_CPS_RSP, 

		/* Peer同步区块涉及消息 */
		EN_QUERY_SYNC_SOURCE_PEER_CS_CPS_REQ,
		EN_QUERY_SYNC_SOURCE_PEER_CPS_CS_RSP,
		EN_GET_BLOCK_CS_CAS_REQ,
		EN_GET_BLOCK_CAS_CS_RSP,
		EN_GET_BLOCK_CAS_CS_REQ,
		EN_GET_BLOCK_CS_CAS_RSP,
		EN_CHECK_BLOCK_HASH_CS_CAS_REQ,
		EN_CHECK_BLOCK_HASH_CAS_CS_RSP,
		EN_VERIFY_PEER_STATE_CS_CAS_REQ,
		EN_VERIFY_PEER_STATE_CAS_CS_RSP,

		/* 注册用户流程涉及消息 */
		EN_REGIST_USER_CLT_CLT_REQ,
		EN_REGIST_USER_CLT_CLT_RSP,
		EN_CRYPT_REGIST_USER_CLT_ES_REQ,
		EN_CRYPT_REGIST_USER_ES_CLT_RSP,
		EN_REGIST_USER_CLT_ES_REQ,
		EN_REGIST_USER_ES_CLT_RSP,
		EN_REGIST_USER_ES_CC_REQ,
		EN_REGIST_USER_CC_ES_RSP,
		EN_CRYPT_SUBMIT_REGIST_USER_TRANSACTION_CLT_ES_REQ,
		EN_CRYPT_SUBMIT_REGIST_USER_TRANSACTION_ES_CLT_RSP,
		EN_SUBMIT_REGIST_USER_TRANSACTION_CLT_ES_REQ,
		EN_SUBMIT_REGIST_USER_TRANSACTION_ES_CLT_RSP,
		EN_SUBMIT_REGIST_USER_TRANSACTION_ES_TAS_REQ,
		EN_SUBMIT_REGIST_USER_TRANSACTION_TAS_ES_RSP,
		EN_SUBMIT_REGIST_USER_TRANSACTION_TAS_CPS_REQ,
		EN_SUBMIT_REGIST_USER_TRANSACTION_CPS_TAS_RSP,


		/* 发起Transaction流程涉及消息 */
		EN_PROPOSE_CLT_CLT_REQ,
		EN_PROPOSE_CLT_CLT_RSP,
		EN_CRYPT_PROPOSE_CLT_ES_REQ,
		EN_CRYPT_PROPOSE_ES_CLT_RSP,
		EN_PROPOSE_CLT_ES_REQ,
		EN_PROPOSE_ES_CLT_RSP,
		EN_QUERY_CRYPT_KEY_PROPOSE_ES_CS_REQ,
		EN_QUERY_CRYPT_KEY_PROPOSE_CS_ES_RSP,
		EN_PROPOSE_ES_CC_REQ,
		EN_PROPOSE_CC_ES_RSP,
		EN_QUERY_WRITE_SET_LIST_PROPOSE_CC_CS_REQ,
		EN_QUERY_WRITE_SET_LIST_PROPOSE_CS_CC_RSP,
		EN_CRYPT_SUBMIT_PROPOSAL_TRANSACTION_CLT_ES_REQ,
		EN_CRYPT_SUBMIT_PROPOSAL_TRANSACTION_ES_CLT_RSP,
		EN_SUBMIT_PROPOSAL_TRANSACTION_CLT_ES_REQ,
		EN_SUBMIT_PROPOSAL_TRANSACTION_ES_CLT_RSP,
		EN_SUBMIT_PROPOSAL_TRANSACTION_ES_TAS_REQ,
		EN_SUBMIT_PROPOSAL_TRANSACTION_TAS_ES_RSP,
		EN_SUBMIT_PROPOSAL_TRANSACTION_TAS_CPS_REQ,
		EN_SUBMIT_PROPOSAL_TRANSACTION_CPS_TAS_RSP,
		EN_DISTRIBUTE_BLOCK_CPS_XCS_REQ,
		EN_DISTRIBUTE_BLOCK_XCS_CPS_RSP,

		/* 查询流程涉及消息 */
		EN_QUERY_CLT_CLT_REQ,
		EN_QUERY_CLT_CLT_RSP,
		EN_CRYPT_QUERY_USER_INFO_CLT_ES_REQ,
		EN_CRYPT_QUERY_USER_INFO_ES_CLT_RSP,
		EN_QUERY_USER_INFO_CLT_ES_REQ,
		EN_QUERY_USER_INFO_ES_CLT_RSP,
		EN_QUERY_CRYPT_KEY_QUERY_ES_CS_REQ,
		EN_QUERY_CRYPT_KEY_QUERY_CS_ES_RSP,
		EN_QUERY_ES_CC_REQ,
		EN_QUERY_CC_ES_RSP,
		EN_QUERY_WRITE_SET_LIST_QUERY_CC_CS_REQ,
		EN_QUERY_WRITE_SET_LIST_QUERY_CS_CC_RSP,
		EN_QUERY_TRANSACTION_QUERY_CC_CS_REQ,
		EN_QUERY_TRANSACTION_QUERY_CS_CC_RSP,
		EN_QUERY_INFORMATION_HISTORY_QUERY_CC_CS_REQ,
		EN_QUERY_INFORMATION_HISTORY__QUERY_CS_CC_RSP,

		EN_QUERY_BLOCK_HEADER_INFO_EXPLORER_CC_CS_REQ,
		EN_QUERY_BLOCK_HEADER_INFO_EXPLORER_CS_CC_RSP,
		EN_QUERY_BLOCK_COUNT_EXPLORER_CC_CS_REQ,
		EN_QUERY_BLOCK_COUNT_EXPLORER_CS_CC_RSP,
		EN_QUERY_WRITE_SET_EXPLORER_CC_XCS_REQ,
		EN_QUERY_WRITE_SET_EXPLORER_CS_CC_RSP,
		EN_QUERY_TRANS_INFO_EXPLORER_CC_CS_REQ,
		EN_QUERY_TRANS_INFO_EXPLORER_CS_CC_RSP,
		EN_QUERY_TRANS_LIST_EXPLORER_CC_CS_REQ,
		EN_QUERY_TRANS_LIST_EXPLORER_CS_CC_RSP,
		EN_QUERY_TRANS_COUNT_EXPLORER_CC_CS_REQ,
		EN_QUERY_TRANS_COUNT_EXPLORER_CS_CC_RSP,

		/*加载outer_cc相关的消息*/
		EN_LOAD_OUTER_CC_CLT_CLT_REQ,
		EN_LOAD_OUTER_CC_CLT_CLT_RSP,
		EN_LOAD_OUTER_CC_CLT_ES_REQ,
		EN_LOAD_OUTER_CC_ES_CLT_RSP,
		EN_LOAD_OUTER_CC_ES_CC_REQ,
		EN_LOAD_OUTER_CC_CC_ES_RSP,
		

		EN_MIN_VBH_MSG = 0X00000320
	};

}

#endif
